kind: GlobalConfig
version: "1.0.0"

spec:

  name: "Gition Development"
  description: "Zero-config local web interface for managing Markdown/MDX documentation and tasks"


  theme:
    primaryColor: "#1dd8f9"
    darkMode: true

  # Feature Configuration
  features:
    taskManagement: true
    realTimeUpdates: true
    search: true
    darkModeToggle: true
    languageSelector: true

  # Task Types
  taskTypes:
    - name: "epic"
      folder: "epics"
      icon: "target"
      color: "#8b5cf6"
    - name: "story"
      folder: "stories"
      icon: "book"
      color: "#3b82f6"
    - name: "bug"
      folder: "bugs"
      icon: "bug"
      color: "#ef4444"
    - name: "task"
      folder: "tasks"
      icon: "check-circle"
      color: "#10b981"
  
  # Development-specific settings
  development:
    debug: true
    logLevel: "info"
    hotReload: true

# # Users
# users:
#   - name: "Romainframe"
#     email: "romain@untereiner.com"
#     role: "Maintainer"

# # Language
# defaultLanguage: "en"

